# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashtag1', models.CharField(max_length=200)),
                ('hashtag2', models.CharField(max_length=200)),
                ('hashtag1_score', models.IntegerField(default=0)),
                ('hashtag2_score', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=10)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=140, unique=True)),
                ('total_number', models.IntegerField(default=0)),
                ('is_synonym', models.BooleanField(default=False)),
                ('is_hashtag', models.BooleanField(default=False)),
                ('last_tweet_id', models.CharField(default='0', max_length=50)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WordUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweets', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_app.Word')),
            ],
        ),
        migrations.AddField(
            model_name='synonym',
            name='synonym_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='battle_app.Word'),
        ),
    ]
