# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashtag1', models.CharField(max_length=200)),
                ('hashtag2', models.CharField(max_length=200)),
                ('hashtag1_score', models.IntegerField(default=0)),
                ('hashtag2_score', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True)),
                ('score', models.CharField(blank=True, max_length=10)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
    ]
