# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0002_auto_20160305_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_app.Word'),
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='synonym_to',
        ),
        migrations.AddField(
            model_name='synonym',
            name='synonym_to',
            field=models.ManyToManyField(related_name='synonym_to', to='battle_app.Word'),
        ),
    ]
