# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0003_auto_20160306_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='synonym_to',
            field=models.ManyToManyField(related_name='synonym_to_word', to='battle_app.Word'),
        ),
    ]
