# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battle_app', '0004_auto_20160306_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battle',
        ),
        migrations.RemoveField(
            model_name='word',
            name='total_number',
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='is_hashtag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='is_synonym',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='last_tweet_id',
            field=models.CharField(default='0', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(editable=False, max_length=140, unique=True),
        ),
    ]
